name: TruffleHog Secrets Scan
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@5f47aad1c2df34f7c6230784ce9a5a659922f479
        with:
          path: ./
          base_depth: 1
          debug: true
